apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notifir.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "notifir.name" . }}
    helm.sh/chart: {{ include "notifir.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "notifir.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.initConfig }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "notifir.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: AUTH_TYPE
            value: {{ .Values.auth.type | quote }}
          - name: CLIENT
            value: pg
          {{- if .Values.postgresql.enabled }}
          - name: DB_DATABASE
            value: {{ .Values.postgresql.auth.database | quote }}
          - name: DB_HOST
            value: {{ include "notifir.postgresql.fullname" . }}
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: {{ .Values.postgresql.auth.username | quote }}
          {{- else }}
          - name: DB_DATABASE
            value: {{ .Values.externalDatabase.database | quote }}
          - name: DB_HOST
            value: {{ .Values.externalDatabase.host | quote }}
          - name: DB_PORT
            value: {{ .Values.externalDatabase.port | quote }}
          - name: DB_USER
            value: {{ .Values.externalDatabase.user | quote }}
          {{- end }}
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "notifir.secret" . }}
                key: {{ include "notifir.secretPasswordKey" . | quote }}
          - name: DB_POSTGRES_USER
            value: postgres
          - name: DB_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "notifir.secret" . }}
                key: {{ include "notifir.secretPostgresPasswordKey" . | quote }}
          {{- if .Values.environment }}
          {{- range $key, $val := .Values.environment }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          {{- if .Values.existingExternalSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingExternalSecret }}
          {{- end }}
          volumeMounts:
          {{- if .Values.initConfig }}
          - mountPath: /notifir/api/init.json
            name: init-config
            subPath: init.json
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.initConfig }}
        - name: init-config
          configMap:
            name: {{ template "notifir.fullname" . }}-initconfig
      {{- end }}
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
