{{- if and (not .Values.postgresql.auth.existingSecret) (not .Values.externalDatabase.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifir.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "notifir.name" . }}
    helm.sh/chart: {{ include "notifir.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ include "notifir.secretPasswordKey" . }}: {{ include "notifir.password" . }}
  {{ include "notifir.secretPostgresPasswordKey" . }}: {{ include "notifir.postgresPassword" . }}
{{- end -}}